name: docker buid
on:
  push:
    branches: 
      [main]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest branches
        uses: actions/checkout@v2

      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v1
