name: docker buid
on:
  push:
    branches: 
      [main]
jobs:
  build-docker-image:
    runs-on: linux/amd64,linux/arm64
    steps:
      -name: Checkout the latest branches
       uses: action/checkout@v2

      -name: Setup docker Buildx
       uses: docker/setup-buildx-action@v1
