name: docker buid
on:
  push:
    branches: 
      [main]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest branches
        uses: actions/checkout@v2

      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/python-helloworld:latest

      - name: Image digest
        run: echo ${{steps.docker_build.outputs}}